"""
Meal Plan Models

Database models for AI-generated meal plans with weekly scheduling.
"""
from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Text, Date, Enum as SQLEnum, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime, date
from app.core.database import Base
import enum


class DietaryPreference(str, enum.Enum):
    """Dietary preference options"""
    NONE = "none"
    VEGETARIAN = "vegetarian"
    VEGAN = "vegan"
    PESCATARIAN = "pescatarian"
    KETO = "keto"
    PALEO = "paleo"
    MEDITERRANEAN = "mediterranean"
    LOW_CARB = "low_carb"
    HIGH_PROTEIN = "high_protein"
    GLUTEN_FREE = "gluten_free"
    DAIRY_FREE = "dairy_free"


class MealPlanStatus(str, enum.Enum):
    """Meal plan status"""
    DRAFT = "draft"
    ACTIVE = "active"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class MealPlan(Base):
    """
    Weekly meal plan generated by AI.

    Contains multiple days of meals with nutrition targets.
    """
    __tablename__ = "meal_plans"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Plan Details
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    start_date = Column(Date, nullable=False, index=True)
    end_date = Column(Date, nullable=False)
    status = Column(SQLEnum(MealPlanStatus), default=MealPlanStatus.DRAFT, nullable=False)

    # Nutrition Targets (daily)
    target_calories = Column(Float, nullable=False, default=2000.0)
    target_protein = Column(Float, nullable=False, default=150.0)
    target_carbs = Column(Float, nullable=False, default=200.0)
    target_fat = Column(Float, nullable=False, default=65.0)

    # Preferences
    dietary_preference = Column(SQLEnum(DietaryPreference), default=DietaryPreference.NONE)
    allergies = Column(String(500), nullable=True)  # Comma-separated list
    excluded_foods = Column(String(500), nullable=True)  # Comma-separated list
    meals_per_day = Column(Integer, default=3)
    include_snacks = Column(Boolean, default=True)

    # AI Generation Info
    ai_provider = Column(String(50), nullable=True)
    ai_model = Column(String(50), nullable=True)
    generation_prompt = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    user = relationship("User", backref="meal_plans")
    days = relationship("MealPlanDay", back_populates="meal_plan", cascade="all, delete-orphan", order_by="MealPlanDay.day_number")

    def __repr__(self):
        return f"<MealPlan(id={self.id}, user_id={self.user_id}, name='{self.name}')>"


class MealPlanDay(Base):
    """
    Single day within a meal plan.

    Contains all meals for that day.
    """
    __tablename__ = "meal_plan_days"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    meal_plan_id = Column(Integer, ForeignKey("meal_plans.id", ondelete="CASCADE"), nullable=False, index=True)

    # Day Info
    day_number = Column(Integer, nullable=False)  # 1-7 for weekly plan
    day_date = Column(Date, nullable=False)
    day_name = Column(String(20), nullable=False)  # Monday, Tuesday, etc.

    # Daily Totals (calculated)
    total_calories = Column(Float, default=0.0)
    total_protein = Column(Float, default=0.0)
    total_carbs = Column(Float, default=0.0)
    total_fat = Column(Float, default=0.0)

    # Notes
    notes = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    meal_plan = relationship("MealPlan", back_populates="days")
    meals = relationship("MealPlanMeal", back_populates="day", cascade="all, delete-orphan", order_by="MealPlanMeal.meal_order")

    def __repr__(self):
        return f"<MealPlanDay(id={self.id}, day={self.day_number}, date={self.day_date})>"


class MealType(str, enum.Enum):
    """Meal type within a day"""
    BREAKFAST = "breakfast"
    MORNING_SNACK = "morning_snack"
    LUNCH = "lunch"
    AFTERNOON_SNACK = "afternoon_snack"
    DINNER = "dinner"
    EVENING_SNACK = "evening_snack"


class MealPlanMeal(Base):
    """
    Individual meal within a meal plan day.

    Contains meal details and nutrition info.
    """
    __tablename__ = "meal_plan_meals"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    day_id = Column(Integer, ForeignKey("meal_plan_days.id", ondelete="CASCADE"), nullable=False, index=True)

    # Meal Info
    meal_type = Column(SQLEnum(MealType), nullable=False)
    meal_order = Column(Integer, nullable=False)  # Order within the day
    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)

    # Recipe/Preparation
    ingredients = Column(Text, nullable=True)  # JSON or newline-separated
    instructions = Column(Text, nullable=True)
    prep_time_minutes = Column(Integer, nullable=True)
    cook_time_minutes = Column(Integer, nullable=True)

    # Nutrition Info
    calories = Column(Float, nullable=False, default=0.0)
    protein = Column(Float, nullable=False, default=0.0)
    carbs = Column(Float, nullable=False, default=0.0)
    fat = Column(Float, nullable=False, default=0.0)
    fiber = Column(Float, nullable=True, default=0.0)

    # Serving Info
    servings = Column(Integer, default=1)
    serving_size = Column(String(50), nullable=True)

    # Status
    is_completed = Column(Boolean, default=False)
    is_skipped = Column(Boolean, default=False)

    # Linked Food Item (optional - for quick logging)
    food_item_id = Column(Integer, ForeignKey("food_items.id", ondelete="SET NULL"), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    day = relationship("MealPlanDay", back_populates="meals")
    food_item = relationship("FoodItem", backref="meal_plan_meals")

    def __repr__(self):
        return f"<MealPlanMeal(id={self.id}, type='{self.meal_type.value}', name='{self.name}')>"


class GroceryList(Base):
    """
    Auto-generated grocery list from meal plan.
    """
    __tablename__ = "grocery_lists"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    meal_plan_id = Column(Integer, ForeignKey("meal_plans.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # List Info
    name = Column(String(100), nullable=False)
    is_completed = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    meal_plan = relationship("MealPlan", backref="grocery_lists")
    user = relationship("User", backref="grocery_lists")
    items = relationship("GroceryItem", back_populates="grocery_list", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<GroceryList(id={self.id}, meal_plan_id={self.meal_plan_id})>"


class GroceryItem(Base):
    """
    Individual item in a grocery list.
    """
    __tablename__ = "grocery_items"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    grocery_list_id = Column(Integer, ForeignKey("grocery_lists.id", ondelete="CASCADE"), nullable=False, index=True)

    # Item Info
    name = Column(String(200), nullable=False)
    quantity = Column(Float, nullable=False, default=1.0)
    unit = Column(String(50), nullable=True)
    category = Column(String(50), nullable=True)  # produce, dairy, meat, etc.

    # Status
    is_purchased = Column(Boolean, default=False)
    notes = Column(String(200), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    grocery_list = relationship("GroceryList", back_populates="items")

    def __repr__(self):
        return f"<GroceryItem(id={self.id}, name='{self.name}', qty={self.quantity})>"
