"""initial schema

Revision ID: b0f8a715c62b
Revises: 
Create Date: 2026-07-07 08:35:58.670553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f8a715c62b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('WORKOUT', 'NUTRITION', 'CONSISTENCY', 'SOCIAL', 'PROGRESS', name='achievementcategory'), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_achievements_category'), 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_slug'), 'achievements', ['slug'], unique=True)
    op.create_table('chat_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('conversation_type', sa.Enum('GENERAL', 'WORKOUT', 'NUTRITION', 'SUPPLEMENTS', 'INJURY', 'MOTIVATION', 'EQUIPMENT', 'TECHNIQUE', name='conversationtype'), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_suggestions_conversation_type'), 'chat_suggestions', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_chat_suggestions_id'), 'chat_suggestions', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_de', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'ABS', 'OBLIQUES', 'CORE', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'HIP_FLEXORS', 'ADDUCTORS', 'ABDUCTORS', 'TRAPS', 'LATS', 'LOWER_BACK', 'NECK', 'FULL_BODY', name='musclegroup'), nullable=False),
    sa.Column('body_part', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'ARMS', 'CORE', 'LEGS', 'GLUTES', 'FULL_BODY', name='bodypart'), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('category', sa.Enum('STRENGTH', 'STRETCHING', 'MOBILITY', 'REHAB', 'CARDIO', 'PLYOMETRIC', 'POWERLIFTING', 'OLYMPIC', 'CALISTHENICS', 'YOGA', 'WARMUP', 'COOLDOWN', name='exercisecategory'), nullable=False),
    sa.Column('equipment', sa.Enum('BODYWEIGHT', 'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'MACHINE', 'CABLE', 'SMITH_MACHINE', 'EZ_BAR', 'TRAP_BAR', 'RESISTANCE_BAND', 'MEDICINE_BALL', 'STABILITY_BALL', 'FOAM_ROLLER', 'PULL_UP_BAR', 'DIP_BARS', 'BENCH', 'BOX', 'TRX', 'NONE', 'OTHER', name='equipment'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNISEX', name='exercisegender'), nullable=False),
    sa.Column('purpose', sa.Enum('HYPERTROPHY', 'STRENGTH', 'ENDURANCE', 'POWER', 'FAT_LOSS', 'REHAB', 'PAIN_RELIEF', 'FLEXIBILITY', 'WARMUP', 'COOLDOWN', 'GENERAL_FITNESS', name='exercisepurpose'), nullable=True),
    sa.Column('pain_focus', sa.Enum('LOWER_BACK', 'UPPER_BACK', 'NECK', 'KNEES', 'SHOULDERS', 'HIPS', 'ANKLES', 'WRISTS', 'ELBOWS', name='painfocus'), nullable=True),
    sa.Column('is_rehab', sa.Boolean(), nullable=True),
    sa.Column('pain_warning', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('force_type', sa.Enum('PUSH', 'PULL', 'STATIC', 'DYNAMIC', name='forcetype'), nullable=True),
    sa.Column('movement_pattern', sa.Enum('HORIZONTAL_PUSH', 'HORIZONTAL_PULL', 'VERTICAL_PUSH', 'VERTICAL_PULL', 'SQUAT', 'HINGE', 'LUNGE', 'ROTATION', 'CARRY', 'ISOLATION', name='movementpattern'), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=True),
    sa.Column('is_unilateral', sa.Boolean(), nullable=True),
    sa.Column('images_male', sa.JSON(), nullable=True),
    sa.Column('images_female', sa.JSON(), nullable=True),
    sa.Column('videos_male', sa.JSON(), nullable=True),
    sa.Column('videos_female', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('gif_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('instructions_de', sa.JSON(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('tips_de', sa.JSON(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.Column('common_mistakes_de', sa.JSON(), nullable=True),
    sa.Column('form_tips', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('musclewiki_id', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('tracks_weight', sa.Boolean(), nullable=True),
    sa.Column('tracks_reps', sa.Boolean(), nullable=True),
    sa.Column('tracks_time', sa.Boolean(), nullable=True),
    sa.Column('tracks_distance', sa.Boolean(), nullable=True),
    sa.Column('default_sets', sa.Integer(), nullable=True),
    sa.Column('default_reps', sa.Integer(), nullable=True),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_spotter', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('musclewiki_id')
    )
    op.create_index('ix_exercise_discover', 'exercises', ['is_active', 'category', 'body_part', 'gender'], unique=False)
    op.create_index('ix_exercise_popular', 'exercises', ['is_active', 'is_popular', 'popularity_score'], unique=False)
    op.create_index('ix_exercise_rehab', 'exercises', ['is_rehab', 'pain_focus', 'is_active'], unique=False)
    op.create_index('ix_exercise_source', 'exercises', ['source', 'musclewiki_id'], unique=False)
    op.create_index(op.f('ix_exercises_body_part'), 'exercises', ['body_part'], unique=False)
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_gender'), 'exercises', ['gender'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_is_active'), 'exercises', ['is_active'], unique=False)
    op.create_index(op.f('ix_exercises_is_compound'), 'exercises', ['is_compound'], unique=False)
    op.create_index(op.f('ix_exercises_is_featured'), 'exercises', ['is_featured'], unique=False)
    op.create_index(op.f('ix_exercises_is_new'), 'exercises', ['is_new'], unique=False)
    op.create_index(op.f('ix_exercises_is_popular'), 'exercises', ['is_popular'], unique=False)
    op.create_index(op.f('ix_exercises_is_rehab'), 'exercises', ['is_rehab'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group'), 'exercises', ['muscle_group'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_pain_focus'), 'exercises', ['pain_focus'], unique=False)
    op.create_index(op.f('ix_exercises_popularity_score'), 'exercises', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_exercises_purpose'), 'exercises', ['purpose'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_index(op.f('ix_exercises_source'), 'exercises', ['source'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('SUPPLEMENTS', 'EQUIPMENT', 'APPAREL', 'ACCESSORIES', 'NUTRITION', 'RECOVERY', 'TECH', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_on_sale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('supplements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PROTEIN', 'VITAMINS', 'MINERALS', 'AMINO_ACIDS', 'PRE_WORKOUT', 'POST_WORKOUT', 'CREATINE', 'BCAA', 'OMEGA_3', 'MULTIVITAMIN', 'WEIGHT_LOSS', 'ENERGY', 'RECOVERY', 'OTHER', name='supplementcategory'), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('default_dosage', sa.Float(), nullable=True),
    sa.Column('dosage_unit', sa.String(length=50), nullable=True),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('calories_per_serving', sa.Integer(), nullable=True),
    sa.Column('protein_per_serving', sa.Float(), nullable=True),
    sa.Column('carbs_per_serving', sa.Float(), nullable=True),
    sa.Column('fats_per_serving', sa.Float(), nullable=True),
    sa.Column('recommended_timing', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'BEFORE_WORKOUT', 'AFTER_WORKOUT', 'WITH_MEAL', 'BEFORE_BED', 'ANY_TIME', name='intaketiming'), nullable=True),
    sa.Column('recommended_frequency', sa.Enum('DAILY', 'WEEKLY', 'AS_NEEDED', 'EVERY_OTHER_DAY', name='intakefrequency'), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplements_category'), 'supplements', ['category'], unique=False)
    op.create_index(op.f('ix_supplements_id'), 'supplements', ['id'], unique=False)
    op.create_index(op.f('ix_supplements_name'), 'supplements', ['name'], unique=True)
    op.create_index(op.f('ix_supplements_slug'), 'supplements', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'COACH', 'ADMIN', 'NUTRITIONIST', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('conversation_type', sa.Enum('GENERAL', 'WORKOUT', 'NUTRITION', 'SUPPLEMENTS', 'INJURY', 'MOTIVATION', 'EQUIPMENT', 'TECHNIQUE', name='conversationtype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_conversation_type'), 'chat_conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('client_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('personal_message', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', 'DECLINED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('last_resend_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_client_invitations_coach_id'), 'client_invitations', ['coach_id'], unique=False)
    op.create_index(op.f('ix_client_invitations_email'), 'client_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_client_invitations_id'), 'client_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_client_invitations_status'), 'client_invitations', ['status'], unique=False)
    op.create_index('ix_invitations_coach_status', 'client_invitations', ['coach_id', 'status'], unique=False)
    op.create_index('ix_invitations_email_coach', 'client_invitations', ['email', 'coach_id'], unique=False)
    op.create_index('ix_invitations_token_hash', 'client_invitations', ['token_hash'], unique=False)
    op.create_table('coach_clients',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id')
    )
    op.create_table('coach_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('is_accepting_clients', sa.Boolean(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_profiles_id'), 'coach_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_coach_profiles_user_id'), 'coach_profiles', ['user_id'], unique=True)
    op.create_table('exercise_alternatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_alternatives_alternative_id'), 'exercise_alternatives', ['alternative_id'], unique=False)
    op.create_index(op.f('ix_exercise_alternatives_exercise_id'), 'exercise_alternatives', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_alternatives_id'), 'exercise_alternatives', ['id'], unique=False)
    op.create_table('exercise_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'ABS', 'OBLIQUES', 'CORE', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'HIP_FLEXORS', 'ADDUCTORS', 'ABDUCTORS', 'TRAPS', 'LATS', 'LOWER_BACK', 'NECK', 'FULL_BODY', name='musclegroup'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group')
    )
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=20), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('saturated_fat', sa.Float(), nullable=True),
    sa.Column('trans_fat', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_barcode'), 'food_items', ['barcode'], unique=True)
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='mealplanstatus'), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=False),
    sa.Column('target_protein', sa.Float(), nullable=False),
    sa.Column('target_carbs', sa.Float(), nullable=False),
    sa.Column('target_fat', sa.Float(), nullable=False),
    sa.Column('dietary_preference', sa.Enum('NONE', 'VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'KETO', 'PALEO', 'MEDITERRANEAN', 'LOW_CARB', 'HIGH_PROTEIN', 'GLUTEN_FREE', 'DAIRY_FREE', name='dietarypreference'), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('excluded_foods', sa.String(length=500), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('include_snacks', sa.Boolean(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plans_start_date'), 'meal_plans', ['start_date'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_date'), 'meals', ['date'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_index('ix_meals_user_date', 'meals', ['user_id', 'date'], unique=False)
    op.create_index('ix_meals_user_date_type', 'meals', ['user_id', 'date', 'meal_type'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('water_ml', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_goals_id'), 'nutrition_goals', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('shipping_name', sa.String(length=255), nullable=False),
    sa.Column('shipping_email', sa.String(length=255), nullable=False),
    sa.Column('shipping_phone', sa.String(length=50), nullable=True),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=False),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=False),
    sa.Column('shipping_state', sa.String(length=100), nullable=False),
    sa.Column('shipping_zip', sa.String(length=20), nullable=False),
    sa.Column('shipping_country', sa.String(length=100), nullable=False),
    sa.Column('billing_address_line1', sa.String(length=255), nullable=True),
    sa.Column('billing_address_line2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_reviews_id'), 'product_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('photo_type', sa.Enum('FRONT', 'BACK', 'SIDE_LEFT', 'SIDE_RIGHT', 'CUSTOM', name='phototype'), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_id'), 'progress_photos', ['id'], unique=False)
    op.create_index(op.f('ix_progress_photos_photo_type'), 'progress_photos', ['photo_type'], unique=False)
    op.create_index(op.f('ix_progress_photos_taken_at'), 'progress_photos', ['taken_at'], unique=False)
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_carts_id'), 'shopping_carts', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_user_id'), 'shopping_carts', ['user_id'], unique=True)
    op.create_table('sleep_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.DateTime(), nullable=False),
    sa.Column('wake_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_sleep_date')
    )
    op.create_index(op.f('ix_sleep_entries_date'), 'sleep_entries', ['date'], unique=False)
    op.create_index(op.f('ix_sleep_entries_id'), 'sleep_entries', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_entries_user_id'), 'sleep_entries', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index('ix_user_achievements_user_unlocked', 'user_achievements', ['user_id', 'is_unlocked'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('last_ip_address', sa.String(length=50), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_last_active'), 'user_devices', ['last_active'], unique=False)
    op.create_index(op.f('ix_user_devices_push_token'), 'user_devices', ['push_token'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'ABS', 'OBLIQUES', 'CORE', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'HIP_FLEXORS', 'ADDUCTORS', 'ABDUCTORS', 'TRAPS', 'LATS', 'LOWER_BACK', 'NECK', 'FULL_BODY', name='musclegroup'), nullable=False),
    sa.Column('body_part', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'ARMS', 'CORE', 'LEGS', 'GLUTES', 'FULL_BODY', name='bodypart'), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('category', sa.Enum('STRENGTH', 'STRETCHING', 'MOBILITY', 'REHAB', 'CARDIO', 'PLYOMETRIC', 'POWERLIFTING', 'OLYMPIC', 'CALISTHENICS', 'YOGA', 'WARMUP', 'COOLDOWN', name='exercisecategory'), nullable=False),
    sa.Column('equipment', sa.Enum('BODYWEIGHT', 'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'MACHINE', 'CABLE', 'SMITH_MACHINE', 'EZ_BAR', 'TRAP_BAR', 'RESISTANCE_BAND', 'MEDICINE_BALL', 'STABILITY_BALL', 'FOAM_ROLLER', 'PULL_UP_BAR', 'DIP_BARS', 'BENCH', 'BOX', 'TRX', 'NONE', 'OTHER', name='equipment'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('tracks_weight', sa.Boolean(), nullable=True),
    sa.Column('tracks_reps', sa.Boolean(), nullable=True),
    sa.Column('tracks_time', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_exercise_user', 'user_exercises', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_exercises_id'), 'user_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_user_exercises_user_id'), 'user_exercises', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('starting_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_goal_type'), 'user_goals', ['goal_type'], unique=False)
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.create_index(op.f('ix_user_levels_user_id'), 'user_levels', ['user_id'], unique=True)
    op.create_table('user_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('left_arm', sa.Float(), nullable=True),
    sa.Column('right_arm', sa.Float(), nullable=True),
    sa.Column('left_thigh', sa.Float(), nullable=True),
    sa.Column('right_thigh', sa.Float(), nullable=True),
    sa.Column('left_calf', sa.Float(), nullable=True),
    sa.Column('right_calf', sa.Float(), nullable=True),
    sa.Column('neck', sa.Float(), nullable=True),
    sa.Column('shoulders', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_measurements_id'), 'user_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_user_measurements_recorded_at'), 'user_measurements', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_user_measurements_user_id'), 'user_measurements', ['user_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sent_via_push', sa.Boolean(), nullable=False),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('sent_via_in_app', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('fitness_level', sa.String(length=20), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_workout_time', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_saved_exercises',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_id'), 'user_streaks', ['id'], unique=False)
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    op.create_table('user_supplements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.Float(), nullable=True),
    sa.Column('dosage_unit', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'AS_NEEDED', 'EVERY_OTHER_DAY', name='intakefrequency'), nullable=False),
    sa.Column('timing', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'BEFORE_WORKOUT', 'AFTER_WORKOUT', 'WITH_MEAL', 'BEFORE_BED', 'ANY_TIME', name='intaketiming'), nullable=False),
    sa.Column('specific_time', sa.Time(), nullable=True),
    sa.Column('days_of_week', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_stock', sa.Integer(), nullable=True),
    sa.Column('remaining_stock', sa.Integer(), nullable=True),
    sa.Column('low_stock_alert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_supplements_id'), 'user_supplements', ['id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_date'), 'water_logs', ['date'], unique=False)
    op.create_index(op.f('ix_water_logs_id'), 'water_logs', ['id'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('STRENGTH', 'HYPERTROPHY', 'POWERLIFTING', 'CARDIO', 'HIIT', 'ENDURANCE', 'FLEXIBILITY', 'CROSSFIT', 'BODYWEIGHT', 'WEIGHT_LOSS', 'MUSCLE_GAIN', 'FULL_BODY', 'UPPER_BODY', 'LOWER_BODY', 'PUSH', 'PULL', 'LEGS', name='workouttype'), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_coach', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_id'), 'workout_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workout_templates_name'), 'workout_templates', ['name'], unique=False)
    op.create_index(op.f('ix_workout_templates_slug'), 'workout_templates', ['slug'], unique=True)
    op.create_index(op.f('ix_workout_templates_workout_type'), 'workout_templates', ['workout_type'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('grocery_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_id'), 'grocery_lists', ['id'], unique=False)
    op.create_index(op.f('ix_grocery_lists_meal_plan_id'), 'grocery_lists', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_grocery_lists_user_id'), 'grocery_lists', ['user_id'], unique=False)
    op.create_table('meal_foods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('serving_amount', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein', sa.Float(), nullable=False),
    sa.Column('total_carbs', sa.Float(), nullable=False),
    sa.Column('total_fat', sa.Float(), nullable=False),
    sa.Column('total_fiber', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_foods_food_id'), 'meal_foods', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_foods_id'), 'meal_foods', ['id'], unique=False)
    op.create_index(op.f('ix_meal_foods_meal_id'), 'meal_foods', ['meal_id'], unique=False)
    op.create_table('meal_plan_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('day_name', sa.String(length=20), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_days_id'), 'meal_plan_days', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plan_days_meal_plan_id'), 'meal_plan_days', ['meal_plan_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('supplement_intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_supplement_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('dosage_taken', sa.Float(), nullable=True),
    sa.Column('dosage_unit', sa.String(length=50), nullable=True),
    sa.Column('was_scheduled', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('side_effects_noted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_supplement_id'], ['user_supplements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_intakes_id'), 'supplement_intakes', ['id'], unique=False)
    op.create_table('user_workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('STRENGTH', 'HYPERTROPHY', 'POWERLIFTING', 'CARDIO', 'HIIT', 'ENDURANCE', 'FLEXIBILITY', 'CROSSFIT', 'BODYWEIGHT', 'WEIGHT_LOSS', 'MUSCLE_GAIN', 'FULL_BODY', 'UPPER_BODY', 'LOWER_BODY', 'PUSH', 'PULL', 'LEGS', name='workouttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('times_completed', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_workouts_id'), 'user_workouts', ['id'], unique=False)
    op.create_index('ix_user_workouts_user_active', 'user_workouts', ['user_id', 'is_active'], unique=False)
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_template_exercises_id'), 'workout_template_exercises', ['id'], unique=False)
    op.create_table('chat_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_feedback_id'), 'chat_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_message_id'), 'chat_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_feedback_user_id'), 'chat_feedback', ['user_id'], unique=False)
    op.create_table('grocery_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grocery_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_items_grocery_list_id'), 'grocery_items', ['grocery_list_id'], unique=False)
    op.create_index(op.f('ix_grocery_items_id'), 'grocery_items', ['id'], unique=False)
    op.create_table('meal_plan_meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'MORNING_SNACK', 'LUNCH', 'AFTERNOON_SNACK', 'DINNER', 'EVENING_SNACK', name='mealtype'), nullable=False),
    sa.Column('meal_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['meal_plan_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_meals_day_id'), 'meal_plan_meals', ['day_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_meals_id'), 'meal_plan_meals', ['id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_workout_id'], ['user_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercises_id'), 'workout_exercises', ['id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_workout_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_workout_id'], ['user_workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_session_client_id_user')
    )
    op.create_index(op.f('ix_workout_sessions_client_id'), 'workout_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_table('exercise_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('user_exercise_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=True),
    sa.Column('sets_completed', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('avg_weight', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('set_details', sa.JSON(), nullable=True),
    sa.Column('is_pr_weight', sa.Boolean(), nullable=True),
    sa.Column('is_pr_reps', sa.Boolean(), nullable=True),
    sa.Column('is_pr_volume', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_exercise_id'], ['user_exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercise_history_exercise', 'exercise_history', ['exercise_id', 'performed_at'], unique=False)
    op.create_index(op.f('ix_exercise_history_id'), 'exercise_history', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_history_performed_at'), 'exercise_history', ['performed_at'], unique=False)
    op.create_index('ix_exercise_history_user_date', 'exercise_history', ['user_id', 'performed_at'], unique=False)
    op.create_index(op.f('ix_exercise_history_user_id'), 'exercise_history', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets_data', sa.Text(), nullable=True),
    sa.Column('total_sets', sa.Integer(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('personal_record', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_id'), 'exercise_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_logs_id'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_exercise_history_user_id'), table_name='exercise_history')
    op.drop_index('ix_exercise_history_user_date', table_name='exercise_history')
    op.drop_index(op.f('ix_exercise_history_performed_at'), table_name='exercise_history')
    op.drop_index(op.f('ix_exercise_history_id'), table_name='exercise_history')
    op.drop_index('ix_exercise_history_exercise', table_name='exercise_history')
    op.drop_table('exercise_history')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_client_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_exercises_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_meal_plan_meals_id'), table_name='meal_plan_meals')
    op.drop_index(op.f('ix_meal_plan_meals_day_id'), table_name='meal_plan_meals')
    op.drop_table('meal_plan_meals')
    op.drop_index(op.f('ix_grocery_items_id'), table_name='grocery_items')
    op.drop_index(op.f('ix_grocery_items_grocery_list_id'), table_name='grocery_items')
    op.drop_table('grocery_items')
    op.drop_index(op.f('ix_chat_feedback_user_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_message_id'), table_name='chat_feedback')
    op.drop_index(op.f('ix_chat_feedback_id'), table_name='chat_feedback')
    op.drop_table('chat_feedback')
    op.drop_index(op.f('ix_workout_template_exercises_id'), table_name='workout_template_exercises')
    op.drop_table('workout_template_exercises')
    op.drop_index('ix_user_workouts_user_active', table_name='user_workouts')
    op.drop_index(op.f('ix_user_workouts_id'), table_name='user_workouts')
    op.drop_table('user_workouts')
    op.drop_index(op.f('ix_supplement_intakes_id'), table_name='supplement_intakes')
    op.drop_table('supplement_intakes')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_meal_plan_days_meal_plan_id'), table_name='meal_plan_days')
    op.drop_index(op.f('ix_meal_plan_days_id'), table_name='meal_plan_days')
    op.drop_table('meal_plan_days')
    op.drop_index(op.f('ix_meal_foods_meal_id'), table_name='meal_foods')
    op.drop_index(op.f('ix_meal_foods_id'), table_name='meal_foods')
    op.drop_index(op.f('ix_meal_foods_food_id'), table_name='meal_foods')
    op.drop_table('meal_foods')
    op.drop_index(op.f('ix_grocery_lists_user_id'), table_name='grocery_lists')
    op.drop_index(op.f('ix_grocery_lists_meal_plan_id'), table_name='grocery_lists')
    op.drop_index(op.f('ix_grocery_lists_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_workout_templates_workout_type'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_slug'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_name'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_id'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_date'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_user_supplements_id'), table_name='user_supplements')
    op.drop_table('user_supplements')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_index(op.f('ix_user_streaks_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_table('user_saved_exercises')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_measurements_user_id'), table_name='user_measurements')
    op.drop_index(op.f('ix_user_measurements_recorded_at'), table_name='user_measurements')
    op.drop_index(op.f('ix_user_measurements_id'), table_name='user_measurements')
    op.drop_table('user_measurements')
    op.drop_index(op.f('ix_user_levels_user_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_goal_type'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_user_exercises_user_id'), table_name='user_exercises')
    op.drop_index(op.f('ix_user_exercises_id'), table_name='user_exercises')
    op.drop_index('ix_user_exercise_user', table_name='user_exercises')
    op.drop_table('user_exercises')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_push_token'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_last_active'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index('ix_user_achievements_user_unlocked', table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_sleep_entries_user_id'), table_name='sleep_entries')
    op.drop_index(op.f('ix_sleep_entries_id'), table_name='sleep_entries')
    op.drop_index(op.f('ix_sleep_entries_date'), table_name='sleep_entries')
    op.drop_table('sleep_entries')
    op.drop_index(op.f('ix_shopping_carts_user_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_id'), table_name='shopping_carts')
    op.drop_table('shopping_carts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_taken_at'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_photo_type'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_id'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.drop_index(op.f('ix_nutrition_goals_id'), table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_user_date_type', table_name='meals')
    op.drop_index('ix_meals_user_date', table_name='meals')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_date'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_start_date'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_barcode'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_table('exercise_muscles')
    op.drop_index(op.f('ix_exercise_alternatives_id'), table_name='exercise_alternatives')
    op.drop_index(op.f('ix_exercise_alternatives_exercise_id'), table_name='exercise_alternatives')
    op.drop_index(op.f('ix_exercise_alternatives_alternative_id'), table_name='exercise_alternatives')
    op.drop_table('exercise_alternatives')
    op.drop_index(op.f('ix_coach_profiles_user_id'), table_name='coach_profiles')
    op.drop_index(op.f('ix_coach_profiles_id'), table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_table('coach_clients')
    op.drop_index('ix_invitations_token_hash', table_name='client_invitations')
    op.drop_index('ix_invitations_email_coach', table_name='client_invitations')
    op.drop_index('ix_invitations_coach_status', table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_status'), table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_id'), table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_email'), table_name='client_invitations')
    op.drop_index(op.f('ix_client_invitations_coach_id'), table_name='client_invitations')
    op.drop_table('client_invitations')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_conversation_type'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplements_slug'), table_name='supplements')
    op.drop_index(op.f('ix_supplements_name'), table_name='supplements')
    op.drop_index(op.f('ix_supplements_id'), table_name='supplements')
    op.drop_index(op.f('ix_supplements_category'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_exercises_source'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_purpose'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_popularity_score'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_pain_focus'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_rehab'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_popular'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_new'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_featured'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_compound'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_active'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_gender'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_body_part'), table_name='exercises')
    op.drop_index('ix_exercise_source', table_name='exercises')
    op.drop_index('ix_exercise_rehab', table_name='exercises')
    op.drop_index('ix_exercise_popular', table_name='exercises')
    op.drop_index('ix_exercise_discover', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_chat_suggestions_id'), table_name='chat_suggestions')
    op.drop_index(op.f('ix_chat_suggestions_conversation_type'), table_name='chat_suggestions')
    op.drop_table('chat_suggestions')
    op.drop_index(op.f('ix_achievements_slug'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_category'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
